[package]
name = "rinflux"
version = "0.9.0"
authors = ["Henrik Jürges <juerges.henrik@gmail.com>"]

[dependencies]
chrono = "~0.4"
influent = "~0.4"
docopt = "~0.8"
log = "~0.3"
simple-logging = "~1.0"
